<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <script src="./js/jquery-3.2.1.js"></script>
  <title>async函数</title>
</head>

<body>
  <script>
    //Promise对象状态变化
    async function f() {
      return 'hello world!'; // return的值为then()的参数
    }
    f().then(v => console.log(v));

    async function f1() {
      throw new Error('error!'); //抛错 reject被catch捕捉
    }
    f1()
      .then(v => console.log(v))
      .catch(e => console.log(e));

    async function getTitle(url) {
      let response = await fetch(url);
      let html = await response.text();
      return html.match(/<title>([\s\S]+)<\/title>/i)[1]; //全部执行完 没有throw error 或reject 然后return
      // 函数getTitle内部有三个操作：抓取网页、取出文本、匹配页面标题。只有这三个操作全部完成，才会执行then方法里面的console.log。
    };

    getTitle('https://tc39.github.io/ecma262/')
      .then(v => console.log(v));
    console.log('over');

    //await命令
    //await命令后面是一个 Promise 对象。如果不是，会被转成一个立即resolve的 Promise 对象。
    async function f2() {
      return await 123; //转换为Promise对象 并立刻resolve 如果throw 被catch捕捉
      //只要一个await语句后面的 Promise 变为reject，那么整个async函数都会中断执行。
    }

    f2().then(v => console.log('await:' + v));
    //异常不中断处理方式
    async function f3() {
      try {
        await Promise.reject('出错了'); //放在try catch中 及时出错了也不会影响后面的执行
      } catch (e) {}
      return await Promise.resolve('await try catch hello world');
    }

    f3().then(v => console.log(v));
    //另一种处理方式
    async function f4() {
      await Promise.reject('await try catch2 出错了')
        .catch(e => console.log(e));
      return await Promise.resolve('await try catch2 hello world');
    }

    f4()
      .then(v => console.log(v))
      .catch(e => console.log(e));

    //多个await同时触发 按照传统写法 浪费时间
    function getTest1(url) {
      return new Promise((resolve, reject) => {
        $.ajax({
          url: 'http://localhost:3000/' + url,
          type: 'GET',
          dataType: 'jsonp',
          success: function (data) {
            if (data) {
              resolve(data.commentURL);
            } else {
              reject('Test1 err');
            }
          }
        })
      })
    };
    //一种方式
    async function f5() {
      let [url1, url2] = await Promise.all([getTest1("test1"), getTest1("test2")]); //同步执行
      console.log(url1);
      console.log(url2);
    }
    f5();

    //另一种方式
    async function f6() {
      let url1Promise = getTest1("test1");
      let url2Promise = getTest1("test2");
      let url1 = await url1Promise;
      let url2 = await url2Promise;
      console.log(url1);
      console.log(url2);
    }
    f6();
    //await只能用在async函数中 用在普通函数中会报错
    // async function dnFuc() {
    //   let urls = ['test1', 'test2', 'test1'];
    //   urls.forEach(function (url) { //报错 await is only valid in async function
    //     await getTest1(url);
    //   })
    // }
    function f7() { //这里不需要aysnc
      let urls = ['test1', 'test2', 'test1'];
      // 可能得到错误结果 forEach 原因是这时三个getTest1()操作将是并发执行，也就是同时执行，而不是继发执行。
      urls.forEach(async function (url) { //在这里async
        let u = await getTest1(url);
        console.log(u);
      });
    }
    f7();

    async function f8() {
      let urls = ['test1', 'test2', 'test1'];
      //for循环相继执行
      for (let url of urls) {
        let u = await getTest1(url);
        console.log(u);
      }
    }
    f8();
    //如果确实希望多个请求并发执行， 可以使用Promise.all方法。 当三个请求都会resolved时， 下面两种写法效果相同。
    // async function dbFuc(db) {
    //   let docs = [{}, {}, {}];
    //   let promises = docs.map((doc) => db.post(doc)); //返回的是Promise对象

    //   let results = await Promise.all(promises);
    //   console.log(results);
    // }

    // // 或者使用下面的写法

    // async function dbFuc(db) {
    //   let docs = [{}, {}, {}];
    //   let promises = docs.map((doc) => db.post(doc));

    //   let results = [];
    //   for (let promise of promises) {
    //     results.push(await promise);
    //   }
    //   console.log(results);
    // }


    // async function logInOrder(urls) {
    //   // 并发读取远程URL
    //   const textPromises = urls.map(async url => {
    //     const response = await fetch(url);
    //     return response.text();
    //   });

    //   // 按次序输出
    //   for (const textPromise of textPromises) {
    //     console.log(await textPromise);
    //   }
    // }
    //上面代码中，虽然map方法的参数是async函数，但它是并发执行的，//同步的
    //因为只有async函数内部是继发执行，外部不受影响。后面的for..of循环内部使用了await，因此实现了按顺序输出。
  </script>
</body>

</html>